# Generated by Django 4.2.4 on 2023-10-10 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('tipos', models.CharField(choices=[('moto', 'Moto'), ('carro', 'Carro'), ('caminhao', 'Caminhão'), ('outros', 'Outros')], max_length=8)),
                ('marca', models.CharField(max_length=20, null=True)),
                ('modelo', models.CharField(max_length=50, null=True)),
                ('ano', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cpf', models.CharField(max_length=11)),
                ('telefone', models.PositiveIntegerField()),
                ('email', models.CharField(max_length=150)),
                ('rua', models.CharField(max_length=100)),
                ('numero', models.PositiveIntegerField()),
                ('cidade', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cpf', models.CharField(max_length=11)),
                ('telefone', models.PositiveIntegerField()),
                ('email', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Manutencoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autoFk', to='Somativa_app.autos')),
                ('funcionarioID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcFk', to='Somativa_app.funcionarios')),
            ],
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('qtde', models.IntegerField()),
                ('codigo', models.CharField(max_length=13)),
                ('fabricante', models.CharField(max_length=150)),
                ('preco_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pagamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desconto', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valorFinal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tipoPag', models.CharField(choices=[('pix', 'PIX'), ('credito', 'CRÉDITO'), ('debito', 'DÉBITO'), ('dinheiro', 'DINHEIRO'), ('outros', 'OUTROS')], max_length=50, null=True)),
                ('status', models.CharField(choices=[('pendente', 'PENDENTE!'), ('aprovado', 'APROVADO!'), ('nao autorizado', 'NÃO AUTORIZADO!')], max_length=50, null=True)),
                ('manutencaoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manut', to='Somativa_app.manutencoes')),
            ],
        ),
        migrations.CreateModel(
            name='ItensManut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtde', models.IntegerField()),
                ('manutencoesID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutFk', to='Somativa_app.manutencoes')),
                ('produtoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prodFk', to='Somativa_app.produtos')),
                ('servicoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servFk', to='Somativa_app.servicos')),
            ],
        ),
    ]
